spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?serverTimezone=GMT%2B8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: dev
    password: dev123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 28770000

resources:
  chain:
   strategy:
     content:
       enabled: true
       paths: /**
   cache: false
   compressed: false
   enabled: false
  cache:
    cachecontrol:
      cache-public: false

server:
  tomcat:
    max-connections: 1000
    max-threads: 1000
    min-spare-threads: 100
    accept-count: 300

image:
  allow:
    type: png|jpg|jpeg|gif|bmp